name: terraform basic workflow

on: 
    push:
    bracches:
      - main

jobs: 
  terraform:
    runs-on: ubuntu-latest


steps: 
- name: Checkout code
  uses: actions/checkout@v4

- name: setup terraform
  uses: hasicorp/setup-terraform@v3

- name: check terraform formatting
  run: terraform fmt -check - recursive

- name: initialize terraform 
  run: terraform init

- name: validate terraform configuration
  run: terraform validate

- name: plan terraform changes
  run: terraform plan
